version: '2'

services:
  app:
    image: 'partner-registry-postgres:latest'
    build:
      context: .
    container_name: partner-registry
    depends_on:
    - db
    ports:
    - 8080:8080
    environment:
    - spring.datasource.url=jdbc:postgresql://db:5432/partnerregistry
    - spring.datasource.username=postgres
    - spring.datasource.password=admin1234
    - spring.jpa.hibernate.ddl-auto=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin1234
    - POSTGRES_DB=partnerregistry


