version: '2'

services:
  frontend:
    container_name: partner-registry-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    restart: always
    depends_on:
      - backend
    networks:
      - frontend
      
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: partner-registry-backend
    depends_on:
    - db
    ports:
    - 8080:8080
    environment:
    - spring.datasource.url=jdbc:postgresql://db:5432/partnerregistry
    - spring.datasource.username=postgres
    - spring.datasource.password=admin1234
    - spring.jpa.hibernate.ddl-auto=update
    networks:
    - backend
    - frontend

  db:
    image: 'postgres:13.1-alpine'
    container_name: partner-registry-db
    ports:
    - 5432:5432
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin1234
    - POSTGRES_DB=partnerregistry
    networks:
    - backend  

networks:
  backend:
  frontend:
