spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerregistry
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
