spring:
  datasource:
    url: jdbc:postgresql://localhost/partnerregistry
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
